// Wire the shared conformance harness against the SQLite implementation,
// scoped to B1's filter pattern per the reviewed B1 plan §1.3.
//
// The harness's make() constructs `new Persistence({ now, generateId })`,
// but `SqliteCaseBoxPersistence` requires a Database. We wrap with a
// per-instance `:memory:` DB created in the constructor.
//
// Filter mechanism (CANONICAL per umbrella §2 + B1 §1.3): the shared
// harness labels every test as `${label}: 6.1.N <description>` (or
// `${label}: R5.N`). We pass label "Sqlite-B1"; node:test's
// `--test-name-pattern` (run via the npm test command in CI) filters
// the run to B1's scope. The B1 conformance pattern is
// `^Sqlite-B1: (?:6\.1\.(?:13a|[1-9]|1[0-5])|R5\.[1-6])(?:\s|$)`.
//
// Preflight assertion (per B1 plan §1.3 + rev-1 reviewer): the runner
// hand-enumerates the expected B1 case ids and asserts they match
// against a list of cases the harness will register (built by reading
// the harness file with the regex). If the count drifts (e.g., harness
// renames a case), the preflight test fails before the full conformance
// run.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { openSqliteCaseBoxPersistence } from "../dist/index.js";
import { runConformance } from "./conformance/runCaseBoxPersistenceConformance.mjs";

// The B1 filter pattern. Tests outside this pattern will throw
// `not_implemented` if invoked; they should be excluded by
// `--test-name-pattern` at runtime.
const B1_PATTERN = /^Sqlite-B1: (?:6\.1\.(?:13a|[1-9]|1[0-5])|R5\.[1-6])(?:\s|$)/;

// Hand-enumerated list of B1 case ids per the reviewed plan §1.3.
// Format matches the harness's `${label}: N <description>` shape.
const B1_EXPECTED_CASE_IDS = [
  "6.1.1", "6.1.2", "6.1.3", "6.1.4", "6.1.5",
  "6.1.6", "6.1.7", "6.1.8", "6.1.9", "6.1.10",
  "6.1.11", "6.1.12", "6.1.13", "6.1.13a", "6.1.14", "6.1.15",
  "R5.1", "R5.2", "R5.3", "R5.4", "R5.5", "R5.6",
];

// Preflight: parse the harness source for the literal label + case-id
// strings (templated as `${label}: <case-id> ...`) and verify the
// regex matches exactly the expected B1 set.
// Preflight: verify the regex matches exactly the expected B1 case set,
// and does NOT match cases outside B1's scope. We do NOT scan the
// harness source for literal IDs because some cases (e.g., 6.1.6/7/8)
// are generated by a runtime loop, so a literal grep would miss them.
// The harness's own conformance run is the authoritative end-to-end
// check — preflight just guards the regex shape against drift.
test("Sqlite-B1 conformance preflight: regex matches exactly the B1 case set", () => {
  // Confirm the harness file is reachable (preflight does not parse it).
  const here = dirname(fileURLToPath(import.meta.url));
  void readFileSync(join(here, "conformance", "runCaseBoxPersistenceConformance.mjs"), "utf8");

  const matched = [];
  for (const id of B1_EXPECTED_CASE_IDS) {
    const synthetic = `Sqlite-B1: ${id} placeholder description`;
    if (B1_PATTERN.test(synthetic)) matched.push(id);
  }
  assert.deepEqual(matched, B1_EXPECTED_CASE_IDS, "B1 regex must match every expected case id");

  // Verify the regex does NOT match cases outside B1's scope (smoke).
  for (const outside of ["6.1.16", "6.1.20", "6.A2.1", "6.A3.1", "R5.7", "R5.9b", "R6.1"]) {
    const synthetic = `Sqlite-B1: ${outside} placeholder description`;
    assert.equal(B1_PATTERN.test(synthetic), false, `${outside} must NOT match B1 pattern`);
  }
});

// Wrapper that satisfies the harness's `new Persistence({ now, generateId })`
// shape by auto-opening a fresh `:memory:` DB per instance. The DB is
// retained as a private field; better-sqlite3 closes the handle when
// the wrapper is garbage-collected (the harness creates one instance
// per test; :memory: DBs are lightweight).
class SqliteCaseBoxPersistenceTestWrapper {
  constructor(opts) {
    const { persistence, db } = openSqliteCaseBoxPersistence({
      path: ":memory:",
      now: opts?.now,
      generateId: opts?.generateId,
    });
    Object.assign(this, persistence);
    // Bind every method so harness can call `p.method(...)` on `this`.
    Object.getOwnPropertyNames(Object.getPrototypeOf(persistence))
      .filter((m) => m !== "constructor" && typeof persistence[m] === "function")
      .forEach((m) => { this[m] = persistence[m].bind(persistence); });
    this._db = db;
  }
}

runConformance("Sqlite-B1", () => ({ Persistence: SqliteCaseBoxPersistenceTestWrapper }));
