// Wire the shared conformance harness against the SQLite implementation,
// scoped to B3's filter pattern per the reviewed B3 plan §1.6.
//
// The harness's make() constructs `new Persistence({ now, generateId })`,
// but `SqliteCaseBoxPersistence` requires a Database. We wrap with a
// per-instance `:memory:` DB created in the constructor.
//
// Filter mechanism (CANONICAL per umbrella §2 + B1/B2/B3 plans §1): the
// shared harness labels every test as `${label}: 6.1.N <description>`
// (or `${label}: R5.N` / `${label}: R6.N`). We pass label "Sqlite-B3";
// node:test's `--test-name-pattern` (run via the npm test command)
// filters the run to B3's scope. The B3 conformance pattern is the
// constant `B3_PATTERN` below; B3 is a SUPERSET of B2 (matter +
// document + R5 + R6.1..R6.3 + getAuditChainHead 6.1.29..6.1.31 +
// audit-read 6.1.32 / 6.1.34..6.1.38).
//
// Preflight assertion (per B1 plan §1.3 + B2 plan §1.5 + B3 plan §1.6):
// the runner hand-enumerates the expected case ids and asserts they match
// against a list of cases the harness will register (built by reading
// the harness file with the regex). If the count drifts (e.g., harness
// renames a case), the preflight test fails before the full conformance
// run.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { openSqliteCaseBoxPersistence } from "../dist/index.js";
import { runConformance } from "./conformance/runCaseBoxPersistenceConformance.mjs";

// The B3 filter pattern (superset of B2: matter cases + matter R5 +
// document cases + document R5 + R6 + 6.1.28 listDocuments cursor
// filter check, PLUS B1 getAuditChainHead cases 6.1.29..6.1.31
// carried forward per B3 plan rev-1 Dim-1 #1, PLUS B3 audit-read
// cases 6.1.32 + 6.1.34..6.1.38). Tests outside this pattern will
// throw `not_implemented` if invoked; they should be excluded by
// `--test-name-pattern` at runtime.
//
// Inner `26-27` alternative is placed BEFORE numeric ranges so the
// regex engine sees the literal combined-case label before trying
// `2[0-8]` (which would consume `26` and then fail the trailing
// `(?:\s|$)` lookahead on the `-`).
const B3_PATTERN = /^Sqlite-B3: (?:6\.1\.(?:13a|26-27|[1-9]|1[0-5]|1[6-9]|2[0-8]|29|30|31|3[2-8])|R5\.(?:[1-9]|9b|1[0-4])|R6\.[1-3])(?:\s|$)/;

// Hand-enumerated list of B3 case ids per the reviewed B3 plan §1.6.
// Format matches the harness's `${label}: N <description>` shape.
const B3_EXPECTED_CASE_IDS = [
  // B1-carried (matter lifecycle 6.1.1..6.1.15 + matter R5)
  "6.1.1", "6.1.2", "6.1.3", "6.1.4", "6.1.5",
  "6.1.6", "6.1.7", "6.1.8", "6.1.9", "6.1.10",
  "6.1.11", "6.1.12", "6.1.13", "6.1.13a", "6.1.14", "6.1.15",
  "R5.1", "R5.2", "R5.3", "R5.4", "R5.5", "R5.6",
  // B2-carried (document lifecycle 6.1.16..6.1.28 + document R5 + R6).
  // Note `6.1.26-27` is a single combined harness test (listDocuments
  // single + multi-page); `6.1.28` is listDocuments cursor-filter check.
  "6.1.16", "6.1.17", "6.1.18", "6.1.19", "6.1.20",
  "6.1.21", "6.1.22", "6.1.23", "6.1.24", "6.1.25",
  "6.1.26-27", "6.1.28",
  "R5.7", "R5.8", "R5.9", "R5.9b", "R5.10", "R5.11", "R5.12", "R5.13", "R5.14",
  "R6.1", "R6.2", "R6.3",
  // R6.4 uses getDocumentDetail (B10 read-aggregation) — out of B2/B3 scope.
  // B1 getAuditChainHead cases CARRIED FORWARD per B3 plan rev-1 Dim-1 #1
  // (previously omitted from B2 regex).
  "6.1.29", "6.1.30", "6.1.31",
  // B3 audit-read cases (6.1.33 does NOT exist in the harness; verified via grep).
  "6.1.32", "6.1.34", "6.1.35", "6.1.36", "6.1.37", "6.1.38",
];

// Preflight: parse the harness source for the literal label + case-id
// strings (templated as `${label}: <case-id> ...`) and verify the
// regex matches exactly the expected B3 set.
// Preflight: verify the regex matches exactly the expected B3 case set,
// and does NOT match cases outside B3's scope. We do NOT scan the
// harness source for literal IDs because some cases (e.g., 6.1.6/7/8)
// are generated by a runtime loop, so a literal grep would miss them.
// The harness's own conformance run is the authoritative end-to-end
// check — preflight just guards the regex shape against drift.
test("Sqlite-B3 conformance preflight: regex matches exactly the B3 case set", () => {
  // Confirm the harness file is reachable (preflight does not parse it).
  const here = dirname(fileURLToPath(import.meta.url));
  void readFileSync(join(here, "conformance", "runCaseBoxPersistenceConformance.mjs"), "utf8");

  const matched = [];
  for (const id of B3_EXPECTED_CASE_IDS) {
    const synthetic = `Sqlite-B3: ${id} placeholder description`;
    if (B3_PATTERN.test(synthetic)) matched.push(id);
  }
  assert.deepEqual(matched, B3_EXPECTED_CASE_IDS, "B3 regex must match every expected case id");

  // Verify the regex does NOT match cases outside B3's scope (smoke).
  // 6.1.29..38 are now in B3 scope; B3 stops there. 6.A2+ is B4+.
  for (const outside of ["6.A2.1", "6.A3.1", "6.A4.1", "6.A5.1", "6.A9.1", "R6.4"]) {
    const synthetic = `Sqlite-B3: ${outside} placeholder description`;
    assert.equal(B3_PATTERN.test(synthetic), false, `${outside} must NOT match B3 pattern`);
  }
});

// Wrapper that satisfies the harness's `new Persistence({ now, generateId })`
// shape by auto-opening a fresh `:memory:` DB per instance. The DB is
// retained as a private field; better-sqlite3 closes the handle when
// the wrapper is garbage-collected (the harness creates one instance
// per test; :memory: DBs are lightweight).
class SqliteCaseBoxPersistenceTestWrapper {
  constructor(opts) {
    const { persistence, db } = openSqliteCaseBoxPersistence({
      path: ":memory:",
      now: opts?.now,
      generateId: opts?.generateId,
    });
    Object.assign(this, persistence);
    // Bind every method so harness can call `p.method(...)` on `this`.
    Object.getOwnPropertyNames(Object.getPrototypeOf(persistence))
      .filter((m) => m !== "constructor" && typeof persistence[m] === "function")
      .forEach((m) => { this[m] = persistence[m].bind(persistence); });
    this._db = db;
  }
}

runConformance("Sqlite-B3", () => ({ Persistence: SqliteCaseBoxPersistenceTestWrapper }));
