// Wire the shared conformance harness against the SQLite implementation,
// scoped to B2's filter pattern per the reviewed B2 plan §1.5.
//
// The harness's make() constructs `new Persistence({ now, generateId })`,
// but `SqliteCaseBoxPersistence` requires a Database. We wrap with a
// per-instance `:memory:` DB created in the constructor.
//
// Filter mechanism (CANONICAL per umbrella §2 + B1/B2 plans §1): the
// shared harness labels every test as `${label}: 6.1.N <description>`
// (or `${label}: R5.N` / `${label}: R6.N`). We pass label "Sqlite-B2";
// node:test's `--test-name-pattern` (run via the npm test command)
// filters the run to B2's scope. The B2 conformance pattern is the
// constant `B2_PATTERN` below; B2 is a SUPERSET of B1 (matter +
// document + R5 + R6 minus R6.4 / aggregations / audit observability).
//
// Preflight assertion (per B1 plan §1.3 + B2 plan §1.5): the runner
// hand-enumerates the expected case ids and asserts they match
// against a list of cases the harness will register (built by reading
// the harness file with the regex). If the count drifts (e.g., harness
// renames a case), the preflight test fails before the full conformance
// run.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { openSqliteCaseBoxPersistence } from "../dist/index.js";
import { runConformance } from "./conformance/runCaseBoxPersistenceConformance.mjs";

// The B2 filter pattern (superset of B1: matter cases + matter R5 +
// document cases + document R5 + R6 + 6.1.28 listDocuments cursor
// filter check). Tests outside this pattern will throw
// `not_implemented` if invoked; they should be excluded by
// `--test-name-pattern` at runtime.
//
// Inner `26-27` alternative is placed BEFORE numeric ranges so the
// regex engine sees the literal combined-case label before trying
// `2[0-8]` (which would consume `26` and then fail the trailing
// `(?:\s|$)` lookahead on the `-`).
const B2_PATTERN = /^Sqlite-B2: (?:6\.1\.(?:13a|26-27|[1-9]|1[0-5]|1[6-9]|2[0-8])|R5\.(?:[1-9]|9b|1[0-4])|R6\.[1-3])(?:\s|$)/;

// Hand-enumerated list of B2 case ids per the reviewed B2 plan §1.5.
// Format matches the harness's `${label}: N <description>` shape.
const B2_EXPECTED_CASE_IDS = [
  // B1-carried (matter lifecycle 6.1.1..6.1.15 + matter R5)
  "6.1.1", "6.1.2", "6.1.3", "6.1.4", "6.1.5",
  "6.1.6", "6.1.7", "6.1.8", "6.1.9", "6.1.10",
  "6.1.11", "6.1.12", "6.1.13", "6.1.13a", "6.1.14", "6.1.15",
  "R5.1", "R5.2", "R5.3", "R5.4", "R5.5", "R5.6",
  // B2 (document lifecycle 6.1.16..6.1.28 + document R5 + R6).
  // Note `6.1.26-27` is a single combined harness test (listDocuments
  // single + multi-page); `6.1.28` is listDocuments cursor-filter check.
  "6.1.16", "6.1.17", "6.1.18", "6.1.19", "6.1.20",
  "6.1.21", "6.1.22", "6.1.23", "6.1.24", "6.1.25",
  "6.1.26-27", "6.1.28",
  "R5.7", "R5.8", "R5.9", "R5.9b", "R5.10", "R5.11", "R5.12", "R5.13", "R5.14",
  "R6.1", "R6.2", "R6.3",
  // R6.4 uses getDocumentDetail (B10 read-aggregation) — out of B2 scope.
];

// Preflight: parse the harness source for the literal label + case-id
// strings (templated as `${label}: <case-id> ...`) and verify the
// regex matches exactly the expected B2 set.
// Preflight: verify the regex matches exactly the expected B2 case set,
// and does NOT match cases outside B2's scope. We do NOT scan the
// harness source for literal IDs because some cases (e.g., 6.1.6/7/8)
// are generated by a runtime loop, so a literal grep would miss them.
// The harness's own conformance run is the authoritative end-to-end
// check — preflight just guards the regex shape against drift.
test("Sqlite-B2 conformance preflight: regex matches exactly the B2 case set", () => {
  // Confirm the harness file is reachable (preflight does not parse it).
  const here = dirname(fileURLToPath(import.meta.url));
  void readFileSync(join(here, "conformance", "runCaseBoxPersistenceConformance.mjs"), "utf8");

  const matched = [];
  for (const id of B2_EXPECTED_CASE_IDS) {
    const synthetic = `Sqlite-B2: ${id} placeholder description`;
    if (B2_PATTERN.test(synthetic)) matched.push(id);
  }
  assert.deepEqual(matched, B2_EXPECTED_CASE_IDS, "B2 regex must match every expected case id");

  // Verify the regex does NOT match cases outside B2's scope (smoke).
  // 6.1.28 IS in B2 scope (listDocuments cursor-filter check); it must
  // be removed from this list. 6.1.29+ is B3 audit observability.
  for (const outside of ["6.1.29", "6.1.30", "6.A2.1", "6.A3.1", "6.A4.1", "6.A5.1", "6.A9.1"]) {
    const synthetic = `Sqlite-B2: ${outside} placeholder description`;
    assert.equal(B2_PATTERN.test(synthetic), false, `${outside} must NOT match B2 pattern`);
  }
});

// Wrapper that satisfies the harness's `new Persistence({ now, generateId })`
// shape by auto-opening a fresh `:memory:` DB per instance. The DB is
// retained as a private field; better-sqlite3 closes the handle when
// the wrapper is garbage-collected (the harness creates one instance
// per test; :memory: DBs are lightweight).
class SqliteCaseBoxPersistenceTestWrapper {
  constructor(opts) {
    const { persistence, db } = openSqliteCaseBoxPersistence({
      path: ":memory:",
      now: opts?.now,
      generateId: opts?.generateId,
    });
    Object.assign(this, persistence);
    // Bind every method so harness can call `p.method(...)` on `this`.
    Object.getOwnPropertyNames(Object.getPrototypeOf(persistence))
      .filter((m) => m !== "constructor" && typeof persistence[m] === "function")
      .forEach((m) => { this[m] = persistence[m].bind(persistence); });
    this._db = db;
  }
}

runConformance("Sqlite-B2", () => ({ Persistence: SqliteCaseBoxPersistenceTestWrapper }));
